function calcRows() {
			var total = 0;
							var val = 0;
									val += parseInt( $('#1_1').val() );
									val += parseInt( $('#1_2').val() );
									val += parseInt( $('#1_3').val() );
									val += parseInt( $('#1_4').val() );
									val += parseInt( $('#1_5').val() );
									val += parseInt( $('#1_6').val() );
									val += parseInt( $('#1_7').val() );
									val += parseInt( $('#1_8').val() );
									val += parseInt( $('#1_9').val() );
									val += parseInt( $('#1_10').val() );
									val += parseInt( $('#1_11').val() );
									val += parseInt( $('#1_12').val() );
									val += parseInt( $('#1_13').val() );
									val += parseInt( $('#1_14').val() );
									val += parseInt( $('#1_15').val() );
									val += parseInt( $('#1_16').val() );
									val += parseInt( $('#1_17').val() );
									val += parseInt( $('#1_18').val() );
								total += val;
				$('#rowtotal-1').text( val );
							var val = 0;
									val += parseInt( $('#2_1').val() );
									val += parseInt( $('#2_2').val() );
									val += parseInt( $('#2_3').val() );
									val += parseInt( $('#2_4').val() );
									val += parseInt( $('#2_5').val() );
									val += parseInt( $('#2_6').val() );
									val += parseInt( $('#2_7').val() );
									val += parseInt( $('#2_8').val() );
									val += parseInt( $('#2_9').val() );
									val += parseInt( $('#2_10').val() );
									val += parseInt( $('#2_11').val() );
									val += parseInt( $('#2_12').val() );
									val += parseInt( $('#2_13').val() );
									val += parseInt( $('#2_14').val() );
									val += parseInt( $('#2_15').val() );
									val += parseInt( $('#2_16').val() );
									val += parseInt( $('#2_17').val() );
									val += parseInt( $('#2_18').val() );
								total += val;
				$('#rowtotal-2').text( val );
							var val = 0;
									val += parseInt( $('#3_1').val() );
									val += parseInt( $('#3_2').val() );
									val += parseInt( $('#3_3').val() );
									val += parseInt( $('#3_4').val() );
									val += parseInt( $('#3_5').val() );
									val += parseInt( $('#3_6').val() );
									val += parseInt( $('#3_7').val() );
									val += parseInt( $('#3_8').val() );
									val += parseInt( $('#3_9').val() );
									val += parseInt( $('#3_10').val() );
									val += parseInt( $('#3_11').val() );
									val += parseInt( $('#3_12').val() );
									val += parseInt( $('#3_13').val() );
									val += parseInt( $('#3_14').val() );
									val += parseInt( $('#3_15').val() );
									val += parseInt( $('#3_16').val() );
									val += parseInt( $('#3_17').val() );
									val += parseInt( $('#3_18').val() );
								total += val;
				$('#rowtotal-3').text( val );
							var val = 0;
									val += parseInt( $('#4_1').val() );
									val += parseInt( $('#4_2').val() );
									val += parseInt( $('#4_3').val() );
									val += parseInt( $('#4_4').val() );
									val += parseInt( $('#4_5').val() );
									val += parseInt( $('#4_6').val() );
									val += parseInt( $('#4_7').val() );
									val += parseInt( $('#4_8').val() );
									val += parseInt( $('#4_9').val() );
									val += parseInt( $('#4_10').val() );
									val += parseInt( $('#4_11').val() );
									val += parseInt( $('#4_12').val() );
									val += parseInt( $('#4_13').val() );
									val += parseInt( $('#4_14').val() );
									val += parseInt( $('#4_15').val() );
									val += parseInt( $('#4_16').val() );
									val += parseInt( $('#4_17').val() );
									val += parseInt( $('#4_18').val() );
								total += val;
				$('#rowtotal-4').text( val );
							var val = 0;
									val += parseInt( $('#5_1').val() );
									val += parseInt( $('#5_2').val() );
									val += parseInt( $('#5_3').val() );
									val += parseInt( $('#5_4').val() );
									val += parseInt( $('#5_5').val() );
									val += parseInt( $('#5_6').val() );
									val += parseInt( $('#5_7').val() );
									val += parseInt( $('#5_8').val() );
									val += parseInt( $('#5_9').val() );
									val += parseInt( $('#5_10').val() );
									val += parseInt( $('#5_11').val() );
									val += parseInt( $('#5_12').val() );
									val += parseInt( $('#5_13').val() );
									val += parseInt( $('#5_14').val() );
									val += parseInt( $('#5_15').val() );
									val += parseInt( $('#5_16').val() );
									val += parseInt( $('#5_17').val() );
									val += parseInt( $('#5_18').val() );
								total += val;
				$('#rowtotal-5').text( val );
							var val = 0;
									val += parseInt( $('#6_1').val() );
									val += parseInt( $('#6_2').val() );
									val += parseInt( $('#6_3').val() );
									val += parseInt( $('#6_4').val() );
									val += parseInt( $('#6_5').val() );
									val += parseInt( $('#6_6').val() );
									val += parseInt( $('#6_7').val() );
									val += parseInt( $('#6_8').val() );
									val += parseInt( $('#6_9').val() );
									val += parseInt( $('#6_10').val() );
									val += parseInt( $('#6_11').val() );
									val += parseInt( $('#6_12').val() );
									val += parseInt( $('#6_13').val() );
									val += parseInt( $('#6_14').val() );
									val += parseInt( $('#6_15').val() );
									val += parseInt( $('#6_16').val() );
									val += parseInt( $('#6_17').val() );
									val += parseInt( $('#6_18').val() );
								total += val;
				$('#rowtotal-6').text( val );
							var val = 0;
									val += parseInt( $('#7_1').val() );
									val += parseInt( $('#7_2').val() );
									val += parseInt( $('#7_3').val() );
									val += parseInt( $('#7_4').val() );
									val += parseInt( $('#7_5').val() );
									val += parseInt( $('#7_6').val() );
									val += parseInt( $('#7_7').val() );
									val += parseInt( $('#7_8').val() );
									val += parseInt( $('#7_9').val() );
									val += parseInt( $('#7_10').val() );
									val += parseInt( $('#7_11').val() );
									val += parseInt( $('#7_12').val() );
									val += parseInt( $('#7_13').val() );
									val += parseInt( $('#7_14').val() );
									val += parseInt( $('#7_15').val() );
									val += parseInt( $('#7_16').val() );
									val += parseInt( $('#7_17').val() );
									val += parseInt( $('#7_18').val() );
								total += val;
				$('#rowtotal-7').text( val );
							var val = 0;
									val += parseInt( $('#8_1').val() );
									val += parseInt( $('#8_2').val() );
									val += parseInt( $('#8_3').val() );
									val += parseInt( $('#8_4').val() );
									val += parseInt( $('#8_5').val() );
									val += parseInt( $('#8_6').val() );
									val += parseInt( $('#8_7').val() );
									val += parseInt( $('#8_8').val() );
									val += parseInt( $('#8_9').val() );
									val += parseInt( $('#8_10').val() );
									val += parseInt( $('#8_11').val() );
									val += parseInt( $('#8_12').val() );
									val += parseInt( $('#8_13').val() );
									val += parseInt( $('#8_14').val() );
									val += parseInt( $('#8_15').val() );
									val += parseInt( $('#8_16').val() );
									val += parseInt( $('#8_17').val() );
									val += parseInt( $('#8_18').val() );
								total += val;
				$('#rowtotal-8').text( val );
										var val = 0;
									val += parseInt( $('#1_1').val() );
									val += parseInt( $('#2_1').val() );
									val += parseInt( $('#3_1').val() );
									val += parseInt( $('#4_1').val() );
									val += parseInt( $('#5_1').val() );
									val += parseInt( $('#6_1').val() );
									val += parseInt( $('#7_1').val() );
									val += parseInt( $('#8_1').val() );
								$('#coltotal-1').text( val );
							var val = 0;
									val += parseInt( $('#1_2').val() );
									val += parseInt( $('#2_2').val() );
									val += parseInt( $('#3_2').val() );
									val += parseInt( $('#4_2').val() );
									val += parseInt( $('#5_2').val() );
									val += parseInt( $('#6_2').val() );
									val += parseInt( $('#7_2').val() );
									val += parseInt( $('#8_2').val() );
								$('#coltotal-2').text( val );
							var val = 0;
									val += parseInt( $('#1_3').val() );
									val += parseInt( $('#2_3').val() );
									val += parseInt( $('#3_3').val() );
									val += parseInt( $('#4_3').val() );
									val += parseInt( $('#5_3').val() );
									val += parseInt( $('#6_3').val() );
									val += parseInt( $('#7_3').val() );
									val += parseInt( $('#8_3').val() );
								$('#coltotal-3').text( val );
							var val = 0;
									val += parseInt( $('#1_4').val() );
									val += parseInt( $('#2_4').val() );
									val += parseInt( $('#3_4').val() );
									val += parseInt( $('#4_4').val() );
									val += parseInt( $('#5_4').val() );
									val += parseInt( $('#6_4').val() );
									val += parseInt( $('#7_4').val() );
									val += parseInt( $('#8_4').val() );
								$('#coltotal-4').text( val );
							var val = 0;
									val += parseInt( $('#1_5').val() );
									val += parseInt( $('#2_5').val() );
									val += parseInt( $('#3_5').val() );
									val += parseInt( $('#4_5').val() );
									val += parseInt( $('#5_5').val() );
									val += parseInt( $('#6_5').val() );
									val += parseInt( $('#7_5').val() );
									val += parseInt( $('#8_5').val() );
								$('#coltotal-5').text( val );
							var val = 0;
									val += parseInt( $('#1_6').val() );
									val += parseInt( $('#2_6').val() );
									val += parseInt( $('#3_6').val() );
									val += parseInt( $('#4_6').val() );
									val += parseInt( $('#5_6').val() );
									val += parseInt( $('#6_6').val() );
									val += parseInt( $('#7_6').val() );
									val += parseInt( $('#8_6').val() );
								$('#coltotal-6').text( val );
							var val = 0;
									val += parseInt( $('#1_7').val() );
									val += parseInt( $('#2_7').val() );
									val += parseInt( $('#3_7').val() );
									val += parseInt( $('#4_7').val() );
									val += parseInt( $('#5_7').val() );
									val += parseInt( $('#6_7').val() );
									val += parseInt( $('#7_7').val() );
									val += parseInt( $('#8_7').val() );
								$('#coltotal-7').text( val );
							var val = 0;
									val += parseInt( $('#1_8').val() );
									val += parseInt( $('#2_8').val() );
									val += parseInt( $('#3_8').val() );
									val += parseInt( $('#4_8').val() );
									val += parseInt( $('#5_8').val() );
									val += parseInt( $('#6_8').val() );
									val += parseInt( $('#7_8').val() );
									val += parseInt( $('#8_8').val() );
								$('#coltotal-8').text( val );
							var val = 0;
									val += parseInt( $('#1_9').val() );
									val += parseInt( $('#2_9').val() );
									val += parseInt( $('#3_9').val() );
									val += parseInt( $('#4_9').val() );
									val += parseInt( $('#5_9').val() );
									val += parseInt( $('#6_9').val() );
									val += parseInt( $('#7_9').val() );
									val += parseInt( $('#8_9').val() );
								$('#coltotal-9').text( val );
							var val = 0;
									val += parseInt( $('#1_10').val() );
									val += parseInt( $('#2_10').val() );
									val += parseInt( $('#3_10').val() );
									val += parseInt( $('#4_10').val() );
									val += parseInt( $('#5_10').val() );
									val += parseInt( $('#6_10').val() );
									val += parseInt( $('#7_10').val() );
									val += parseInt( $('#8_10').val() );
								$('#coltotal-10').text( val );
							var val = 0;
									val += parseInt( $('#1_11').val() );
									val += parseInt( $('#2_11').val() );
									val += parseInt( $('#3_11').val() );
									val += parseInt( $('#4_11').val() );
									val += parseInt( $('#5_11').val() );
									val += parseInt( $('#6_11').val() );
									val += parseInt( $('#7_11').val() );
									val += parseInt( $('#8_11').val() );
								$('#coltotal-11').text( val );
							var val = 0;
									val += parseInt( $('#1_12').val() );
									val += parseInt( $('#2_12').val() );
									val += parseInt( $('#3_12').val() );
									val += parseInt( $('#4_12').val() );
									val += parseInt( $('#5_12').val() );
									val += parseInt( $('#6_12').val() );
									val += parseInt( $('#7_12').val() );
									val += parseInt( $('#8_12').val() );
								$('#coltotal-12').text( val );
							var val = 0;
									val += parseInt( $('#1_13').val() );
									val += parseInt( $('#2_13').val() );
									val += parseInt( $('#3_13').val() );
									val += parseInt( $('#4_13').val() );
									val += parseInt( $('#5_13').val() );
									val += parseInt( $('#6_13').val() );
									val += parseInt( $('#7_13').val() );
									val += parseInt( $('#8_13').val() );
								$('#coltotal-13').text( val );
							var val = 0;
									val += parseInt( $('#1_14').val() );
									val += parseInt( $('#2_14').val() );
									val += parseInt( $('#3_14').val() );
									val += parseInt( $('#4_14').val() );
									val += parseInt( $('#5_14').val() );
									val += parseInt( $('#6_14').val() );
									val += parseInt( $('#7_14').val() );
									val += parseInt( $('#8_14').val() );
								$('#coltotal-14').text( val );
							var val = 0;
									val += parseInt( $('#1_15').val() );
									val += parseInt( $('#2_15').val() );
									val += parseInt( $('#3_15').val() );
									val += parseInt( $('#4_15').val() );
									val += parseInt( $('#5_15').val() );
									val += parseInt( $('#6_15').val() );
									val += parseInt( $('#7_15').val() );
									val += parseInt( $('#8_15').val() );
								$('#coltotal-15').text( val );
							var val = 0;
									val += parseInt( $('#1_16').val() );
									val += parseInt( $('#2_16').val() );
									val += parseInt( $('#3_16').val() );
									val += parseInt( $('#4_16').val() );
									val += parseInt( $('#5_16').val() );
									val += parseInt( $('#6_16').val() );
									val += parseInt( $('#7_16').val() );
									val += parseInt( $('#8_16').val() );
								$('#coltotal-16').text( val );
							var val = 0;
									val += parseInt( $('#1_17').val() );
									val += parseInt( $('#2_17').val() );
									val += parseInt( $('#3_17').val() );
									val += parseInt( $('#4_17').val() );
									val += parseInt( $('#5_17').val() );
									val += parseInt( $('#6_17').val() );
									val += parseInt( $('#7_17').val() );
									val += parseInt( $('#8_17').val() );
								$('#coltotal-17').text( val );
							var val = 0;
									val += parseInt( $('#1_18').val() );
									val += parseInt( $('#2_18').val() );
									val += parseInt( $('#3_18').val() );
									val += parseInt( $('#4_18').val() );
									val += parseInt( $('#5_18').val() );
									val += parseInt( $('#6_18').val() );
									val += parseInt( $('#7_18').val() );
									val += parseInt( $('#8_18').val() );
								$('#coltotal-18').text( val );
						$('#settotal').text( total );

							var total = 0;
									var val = 0;
											val += parseInt( $('#9_1').val() );
											val += parseInt( $('#9_2').val() );
											val += parseInt( $('#9_3').val() );
											val += parseInt( $('#9_4').val() );
											val += parseInt( $('#9_5').val() );
											val += parseInt( $('#9_6').val() );
											val += parseInt( $('#9_7').val() );
										total += val;
					$('#b2-rowtotal-9').text( val );
									var val = 0;
											val += parseInt( $('#10_1').val() );
											val += parseInt( $('#10_2').val() );
											val += parseInt( $('#10_3').val() );
											val += parseInt( $('#10_4').val() );
											val += parseInt( $('#10_5').val() );
											val += parseInt( $('#10_6').val() );
											val += parseInt( $('#10_7').val() );
										total += val;
					$('#b2-rowtotal-10').text( val );
									var val = 0;
											val += parseInt( $('#11_1').val() );
											val += parseInt( $('#11_2').val() );
											val += parseInt( $('#11_3').val() );
											val += parseInt( $('#11_4').val() );
											val += parseInt( $('#11_5').val() );
											val += parseInt( $('#11_6').val() );
											val += parseInt( $('#11_7').val() );
										total += val;
					$('#b2-rowtotal-11').text( val );
									var val = 0;
											val += parseInt( $('#12_1').val() );
											val += parseInt( $('#12_2').val() );
											val += parseInt( $('#12_3').val() );
											val += parseInt( $('#12_4').val() );
											val += parseInt( $('#12_5').val() );
											val += parseInt( $('#12_6').val() );
											val += parseInt( $('#12_7').val() );
										total += val;
					$('#b2-rowtotal-12').text( val );
													var val = 0;
											val += parseInt( $('#9_1').val() );
											val += parseInt( $('#10_1').val() );
											val += parseInt( $('#11_1').val() );
											val += parseInt( $('#12_1').val() );
										$('#b2-coltotal-1').text( val );
									var val = 0;
											val += parseInt( $('#9_2').val() );
											val += parseInt( $('#10_2').val() );
											val += parseInt( $('#11_2').val() );
											val += parseInt( $('#12_2').val() );
										$('#b2-coltotal-2').text( val );
									var val = 0;
											val += parseInt( $('#9_3').val() );
											val += parseInt( $('#10_3').val() );
											val += parseInt( $('#11_3').val() );
											val += parseInt( $('#12_3').val() );
										$('#b2-coltotal-3').text( val );
									var val = 0;
											val += parseInt( $('#9_4').val() );
											val += parseInt( $('#10_4').val() );
											val += parseInt( $('#11_4').val() );
											val += parseInt( $('#12_4').val() );
										$('#b2-coltotal-4').text( val );
									var val = 0;
											val += parseInt( $('#9_5').val() );
											val += parseInt( $('#10_5').val() );
											val += parseInt( $('#11_5').val() );
											val += parseInt( $('#12_5').val() );
										$('#b2-coltotal-5').text( val );
									var val = 0;
											val += parseInt( $('#9_6').val() );
											val += parseInt( $('#10_6').val() );
											val += parseInt( $('#11_6').val() );
											val += parseInt( $('#12_6').val() );
										$('#b2-coltotal-6').text( val );
									var val = 0;
											val += parseInt( $('#9_7').val() );
											val += parseInt( $('#10_7').val() );
											val += parseInt( $('#11_7').val() );
											val += parseInt( $('#12_7').val() );
										$('#b2-coltotal-7').text( val );
								$('#b2-settotal').text( total );

		}